# Generated by Django 4.0.4 on 2022-05-21 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermitApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('N', 'New'), ('RN', 'Renew')], max_length=2)),
                ('business_name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('trade_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trade/Franchise Name')),
                ('business_type', models.CharField(choices=[('1', 'Sole Proprietorship'), ('2', 'Partnership'), ('3', 'Corporation'), ('4', 'Cooperative')], default='1', max_length=1, verbose_name='Type of business')),
                ('corporation_type', models.CharField(choices=[('1', 'Filipino'), ('2', 'Foreign')], default='1', max_length=1, verbose_name='For Corporation')),
                ('registration_number', models.CharField(max_length=128, verbose_name='DTI/SEC/CDA Registration Number')),
                ('tax_id_number', models.CharField(max_length=128, verbose_name='Tax Identification Number')),
                ('tel_no', models.CharField(max_length=20, verbose_name='Tel No.')),
                ('mobile_no', models.CharField(max_length=20, verbose_name='Mobile No.')),
                ('email_address', models.CharField(max_length=255, verbose_name='Email Address')),
                ('house_bldg_no', models.CharField(max_length=50, verbose_name='House/Bldg No.')),
                ('blgd_name', models.CharField(max_length=255, verbose_name='Building Name')),
                ('block_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Block No.')),
                ('lot_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lot No.')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street')),
                ('barangay', models.CharField(max_length=100, verbose_name='Barangay')),
                ('city', models.CharField(default='Tanauan City', max_length=100, verbose_name='City')),
                ('province', models.CharField(default='Batangas', max_length=100, verbose_name='Province')),
                ('zip_code', models.CharField(default='4232', max_length=100, verbose_name='Zip Code')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('given_name', models.CharField(max_length=255, verbose_name='Given Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('owned', models.BooleanField(default=True, verbose_name='I am the business owner')),
                ('rented', models.BooleanField(default=False, verbose_name='The business rents a property')),
                ('tax_declaration', models.CharField(max_length=100, verbose_name='Tax Declaration')),
                ('property_ident_no', models.CharField(max_length=100, verbose_name='Property Identification No.')),
                ('capital_investment', models.FloatField(verbose_name='Paid up Capital + Lease Expenses + Equipments')),
                ('tax_incentives', models.BooleanField(default=False, verbose_name='Tax incentives from government entity')),
                ('business_area', models.CharField(max_length=100, verbose_name='Business Area(in sq. m)')),
                ('total_floor_area', models.CharField(max_length=100, verbose_name='Total Floor Area (in sq.m.)')),
                ('female_emp_count', models.IntegerField(default=0, verbose_name='Female')),
                ('male_emp_count', models.IntegerField(default=0, verbose_name='Male')),
                ('tanauan_emp_count', models.IntegerField(default=0, verbose_name='Residing within Tanauan City')),
                ('van_truck_count', models.IntegerField(default=0, verbose_name='Van/Truck')),
                ('motorcycle_count', models.IntegerField(default=0, verbose_name='Motorcycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.ImageField(upload_to='requirements/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.businesspermitapplication')),
            ],
        ),
    ]
