# Generated by Django 4.0.4 on 2022-05-21 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.businesspermitapplication'),
        ),
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_line', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
                ('capital_investment', models.FloatField()),
                ('essential', models.FloatField()),
                ('non_essential', models.FloatField()),
                ('business_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.businesspermitapplication')),
            ],
        ),
    ]
