# Generated by Django 4.0.4 on 2022-05-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_requirement_delete_requirements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
