# Generated by Django 4.0.4 on 2022-05-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_requirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessActivity',
        ),
    ]
