# Generated by Django 4.0.4 on 2022-05-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_delete_businessactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('business_line', models.CharField(max_length=255)),
                ('no_units', models.IntegerField()),
                ('capital_investment', models.FloatField()),
                ('essential', models.FloatField()),
                ('non_essential', models.FloatField()),
                ('business_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.businesspermitapplication')),
            ],
        ),
    ]
