# Generated by Django 4.0.4 on 2022-05-23 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_businessactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='business_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.businesspermitapplication'),
        ),
    ]
