# Generated by Django 4.0.4 on 2022-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_businessactivity_business_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='block_no',
            field=models.CharField(max_length=50, null=True, verbose_name='Block No.'),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='capital_investment',
            field=models.FloatField(default=0.0, verbose_name='Paid up Capital + Lease Expenses + Equipments'),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='lot_no',
            field=models.CharField(max_length=50, null=True, verbose_name='Lot No.'),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='middle_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='owned',
            field=models.BooleanField(default=False, verbose_name='I am the business owner'),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='street',
            field=models.CharField(max_length=50, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='trade_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Trade/Franchise Name'),
        ),
    ]
