# Generated by Django 4.0.4 on 2022-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_businesspermitapplication_block_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermitapplication',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspermitapplication',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
