# Generated by Django 4.0.4 on 2022-05-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_businesspermitapplication_submitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspermitapplication',
            name='lot_no',
        ),
        migrations.AddField(
            model_name='businesspermitapplication',
            name='subdivision',
            field=models.CharField(max_length=100, null=True, verbose_name='Subdivision.'),
        ),
    ]
