# Generated by Django 4.0.4 on 2022-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_businesspermitapplication_lot_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermitapplication',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesspermitapplication',
            name='processed_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='businesspermitapplication',
            name='submission_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='block_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Block No.'),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='subdivision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subdivision.'),
        ),
    ]
