# Generated by Django 4.0.4 on 2022-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_businesspermitapplication_denied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesspermitapplication',
            old_name='processed_timestamp',
            new_name='application_timestamp',
        ),
        migrations.RemoveField(
            model_name='businesspermitapplication',
            name='denied',
        ),
        migrations.RemoveField(
            model_name='businesspermitapplication',
            name='submitted',
        ),
        migrations.RemoveField(
            model_name='businesspermitapplication',
            name='verified',
        ),
        migrations.AddField(
            model_name='businesspermitapplication',
            name='application_status',
            field=models.CharField(blank=True, choices=[('processing', 'Processing'), ('completed', 'Completed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='businesspermitapplication',
            name='submission_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('denied', 'Denied'), ('submitted', 'Submitted')], max_length=20, null=True),
        ),
    ]
