# Generated by Django 4.0.4 on 2022-06-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_rename_processed_timestamp_businesspermitapplication_application_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesspermitapplication',
            options={'ordering': ['-submission_timestamp']},
        ),
        migrations.AlterField(
            model_name='businesspermitapplication',
            name='submission_status',
            field=models.CharField(blank=True, choices=[('VERIFIED', 'Verified'), ('DENIED', 'Denied'), ('SUBMITTED', 'Submitted')], max_length=20, null=True),
        ),
    ]
