# Generated by Django 4.0.4 on 2022-06-01 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0014_alter_businesspermitapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermit',
            fields=[
                ('bpa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.businesspermitapplication')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
